#!/usr/bin/env bash
#
# get a tag as first argument and message id as second argument
#

if [[ -z "$1" ]] || [[ -z "$2" ]]; then
	exit 1
fi

if [[ $(notmuch search "id:$2" and "tag:$1") ]]; then # check if the message matches the tag
  echo "removing tag: $1 from id:$2"              # 
  notmuch tag "-$1" "thread:$2"                           # remove the tag
else
  echo "adding tag: $1 to id:$2"                  #
  notmuch tag "+$1" "thread:$2"                           # add the tag
fi
