config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  ignoreempty: false
  keepdot: true
  link_on_import: link_children
  link_dotfile_default: link
  longkey: true
  showdiff: true
  workdir: ~/.cache/dotdrop
  cmpignore:
    - 'nvim/plugged'
    - 'zsh/.zprezto'
  upignore:
    - 'nvim/plugged'
    - 'zsh/.zprezto'
    - 'weechat/logs'
    - '*/.config/*'
dotfiles:
  d_config:
    src: config
    dst: ~/.config
    link: link_children
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    link: link_children
  d_config_base16:
    src: config/base16-shell
    dst: ~/.config/base16-shell
    link: link
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    link: link
  d_local_bin:
    dst: ~/.local/bin
    link: link
    src: local/bin
  d_local_share_pandoc:
    dst: ~/.local/share/pandoc
    link: link
    src: local/share/pandoc
  d_weechat:
    dst: ~/.weechat
    link: link_children
    src: weechat
  f_gitconfig:
    dst: ~/.gitconfig
    link: link
    src: gitconfig
  f_gnupg_gpg.conf:
    dst: ~/.gnupg/gpg.conf
    link: link
    src: gnupg/gpg.conf
  f_latexmkrc:
    dst: ~/.latexmkrc
    link: link
    src: latexmkrc
  f_signature:
    src: ../docs/private-dotfiles/signature
    dst: ~/.signature
    link: link
  f_config_neomutt_neomuttrc:
    src: ../docs/private-dotfiles/neomuttrc
    dst: ~/.config/neomutt/neomuttrc
    link: link
  f_tmux.conf:
    dst: ~/.tmux.conf
    link: link
    src: tmux.conf
  f_xresources:
    dst: ~/.Xresources
    link: link
    src: Xresources
  f_zshenv:
    dst: ~/.zshenv
    link: link
    src: zshenv
profiles:
  delta-alpha:
    include:
    - shared
  lincoln-delta:
    include:
    - shared
  lincoln-echo:
    include:
    - shared
  private:
    dotfiles:
    - f_signature
    - f_config_neomutt_neomuttrc
  shared:
    include:
      - private
    dotfiles:
    - d_config_nvim
    - d_config
    - d_config_base16
    - d_config_zsh
    - d_local_bin
    - d_local_share_pandoc
    - d_weechat
    - f_latexmkrc
    - f_gitconfig
    - f_xresources
    - f_zshenv
    - f_gnupg_gpg.conf
    - f_tmux.conf
