config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles
  ignoreempty: false
  keepdot: false
  link_by_default: true
  longkey: true
  showdiff: true
  workdir: ~/.cache/dotdrop
dotfiles:
  d_config_base16:
    dst: ~/.config/base16-shell
    link: true
    src: config/base16-shell
  d_config_i3:
    dst: ~/.config/i3
    link: true
    src: config/i3
  d_config_systemd:
    dst: ~/.config/systemd
    link: true
    src: config/systemd
  d_config_urlwatch:
    dst: ~/.config/urlwatch
    link: true
    src: config/urlwatch
  d_config_zsh:
    dst: ~/.config/zsh
    link: true
    src: config/zsh
  d_local_bin:
    dst: ~/.local/bin
    link: true
    src: local/bin
  d_local_share_pandoc:
    dst: ~/.local/share/pandoc
    link: true
    src: local/share/pandoc
  f_config_nvim:
    dst: ~/.config/nvim/
    link_children: true
    src: config/nvim/
  f_config_polybar:
    dst: ~/.config/polybar/config
    link: true
    src: config/polybar/config
  f_config_termite_config:
    dst: ~/.config/termite/config
    link: true
    src: config/termite/config
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_gnupg_gpg.conf:
    dst: ~/.gnupg/gpg.conf
    link: true
    src: gnupg/gpg.conf
  f_tmux.conf:
    dst: ~/.tmux.conf
    link: true
    src: tmux.conf
  f_xresources:
    dst: ~/.Xresources
    link: true
    src: Xresources
  f_zshenv:
    dst: ~/.zshenv
    link: true
    src: zshenv
profiles:
  delta-alpha:
    dotfiles: []
    include:
    - shared
  lincoln-delta:
    dotfiles: []
    include:
    - shared
  lincoln-echo:
    dotfiles: []
    include:
    - shared
  shared:
    dotfiles:
    - f_config_polybar
    - f_gitconfig
    - d_config_zsh
    - d_config_base16
    - d_local_bin
    - f_xresources
    - f_zshenv
    - f_config_nvim
    - d_config_i3
    - f_gnupg_gpg.conf
    - f_config_termite_config
    - f_tmux.conf
    - d_local_share_pandoc
    - d_config_systemd
    - d_config_urlwatch
