# Example of a job to watch a URL
---
name: "film fra sør: program"
kind: url
url: "https://filmfrasor.no/no/program"
filter:
  - css:
      selector: '.program_allfilms a.card'
      sort: true
  - html2text
