"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[revsets]
log = 'present(trunk()..@) | ancestors(bookmarks() | tracked_remote_bookmarks()::, 2) | present(trunk())'

[user]
name = "Thor K. Høgås"
email = "thor@roht.no"

[merge-tools.nvim]
program = "nvim"
edit-args = ["-c", "DiffEditor $left $right $output"]
merge-args = ["-d", "-o", "$left", "$base", "$right", "$output"]
merge-tool-edits-conflict-markers = true

[merge-tools.hunk]
program = "nvim"
merge-args = ["-c", "DiffEditor $left $right $output"]
merge-tool-edits-conflict-markers = true

[merge-tools.delta]
# Supress warning on exit
diff-expected-exit-codes = [0, 1]

[[--scope]]
--when.commands = ["diff", "show", "log"]
[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff-formatter = ":git"

[signing]
behaviour = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519_work.pub"

[templates]
git_push_bookmark = '"thor/push-" ++ change_id.short()'

[git]
# Automatically sign commits when pushing them
sign-on-push = true
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"

[fsmonitor]
backend = "watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true
