#!/bin/bash

if command -v nvim >/dev/null 2>&1; then
	if [ ! -f "$HOME/.config/nvim/autoload/plug.vim" ]; then
		echo "Bootstrapping nvim"
		curl --create-dirs -fsSLo ~/.config/nvim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
	fi

	if [ ! -d "$HOME/.config/nvim/plugged" ]; then
		echo "Installing nvim plugins"
		nvim '+PlugClean!' '+PlugInstall' '+PlugUpdate' '+qall'
	fi
fi

