#!/bin/bash

if command -v nvim >/dev/null 2>&1; then
	echo "Bootstrapping neovim"
	if [ ! -f "~/.config/nvim/autoload/plug.vim" ]; then
		curl --create-dirs -fsSLo ~/.config/nvim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
	fi
	nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

